### ISSUE TITLE
Weird interaction with httpretty

### ISSUE THREAD

**Issue by cdown** [wolever/nose-parameterized#30]
Reported over there, but I don't know where the bug exists here. Maybe it's even just a documentation issue.

https://github.com/gabrielfalcao/HTTPretty/issues/259

**Comment by wolever** [comment]
I'm not 100% sure why the tests wouldn't be running when the HTTPretty decorator comes first (`@parameterized` creates returns a generator, and `@httpretty.activate` seems to return the function result)… but nose does a _lot_ of magic, so surprising things like this are par for the course :)

In either case, though, the `@httpretty.activate` should definitely come second (otherwise, even if everything worked correctly, it would wrap all the parameterized tests, not each individual test). This seems like a good thing to document — I'll drop it in next time I update the docs.

Thanks!
